### ISSUE TITLE
Browser

### ISSUE THREAD

**Issue by artyprog** [anthonygore/vue-clock-simple#1]
Hy,

I can't make it run on browser.
How I can access the VueClock component globally in window.

I don't undetstab how you use  VueClock l"ibrary" in the browser 

Regards

**Comment by anthonygore** [comment]
The file to use in the browser is dist/vue-clock.min.js. I recommend you read the article that explains this: https://vuejsdevelopers.com/2017/07/31/vue-component-publish-npm/
